### ISSUE TITLE
issue with win-builder?

### ISSUE THREAD

**Issue by fmichonneau** [ropensci/fulltext#79] opened 2016-01-20 20:29 UTC
For some reason this (from one of the [rotl](https://github.com/ropensci/rot) vignettes) fails on win-builder (but not on my linux boxes). I don't know if it's because of an intricacy with win-builder or that something is wrong with fulltext.

```
library(fulltext)

ft_get_si("10.1111/jeb.12282", 1, save.name="egg.xls")
```

**Comment by sckott** [comment] 2016-01-20 20:34
What is the error?

**Comment by fmichonneau** [comment] 2016-01-20 20:43
Here is the error:

```
Error in get_si_pub(doi) : 
    Cannot find publisher for DOI: 10.1111/jeb.12282
```

**Comment by sckott** [comment] 2016-01-20 20:45
thx, looking

**Comment by sckott** [comment] 2016-01-20 20:57
Yep, I get the same error with the CRAN version   - however, fixed in the current github dev version. maybe it was this PR #73 - not sure

paging @willpearse as he made the fix

maybe I'll spin up a new milestone for a patch version to push to CRAN - i assume it's best if this is fixed soon so `rotl` doesn't have to deal with the error @fmichonneau

**Comment by fmichonneau** [comment] 2016-01-20 21:16
Great, good to know that it's already fixed!

I need to submit rotl to CRAN (following the request to one of the maintainers) soon, but I suspect we will submit another version once we get the reviews back from the manuscript (if we ever get them back...)

**Comment by sckott** [comment] 2016-01-20 21:17
> I need to submit rotl to CRAN (following the request to one of the maintainers) soon,

when?  I can submit a patch version to CRAN before you submit if you want

**Comment by willpearse** [comment] 2016-01-20 21:20
...I'm checking it on a friend's Windows computer now...

**Comment by willpearse** [comment] 2016-01-20 21:31
All good, works fine using the GitHub version @fmichonneau , so patch away @sckott 

...which is more than I can say for the ease of installing ```devtools ``` et al. on a PC, but that's a rant for another time/day...!

**Comment by sckott** [comment] 2016-01-20 21:52
glad it works on the pc.

**Comment by fmichonneau** [comment] 2016-01-20 22:46
Thanks for being so responsive.

Yes, if you are ready for a patch release on CRAN that would be great!

**Comment by sckott** [comment] 2016-01-20 23:32
okay, new milestone https://github.com/ropensci/fulltext/milestones/v0.1.6 will go soon

**Comment by sckott** [comment] 2016-01-21 23:47
submitting soon, closing

**Closed by sckott** 2016-01-21 23:47 UTC

**Comment by sckott** [comment] 2016-01-22 01:09
https://github.com/ropensci/fulltext/releases/tag/v0.1.6 sent to cran

**Comment by fmichonneau** [comment] 2016-01-30 17:37
Sorry, but it looks this still hangs on win-builder both with R 3.2.3 and R-devel (at least on the 32-bit architecture).

```r
R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: i386-w64-mingw32/i386 (32-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> ## ----egg_data, cache=TRUE------------------------------------------------
> library(readxl)
> library(rotl)
> library(fulltext)
> packageVersion("fulltext")
[1] '0.1.6'
> 
> doi <- "10.1111/jeb.12282"
> egg_data <- read_excel( path = ft_get_si(doi, 1, save.name="egg.xls") )
```

with R-devel

```r
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: i386-w64-mingw32/i386 (32-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> ## ----egg_data, cache=TRUE------------------------------------------------
> library(readxl)
> library(rotl)
> library(fulltext)
> packageVersion("fulltext")
[1] '0.1.6'
> 
> doi <- "10.1111/jeb.12282"
> egg_data <- read_excel( path = ft_get_si(doi, 1, save.name="egg.xls") )
```

**Comment by willpearse** [comment] 2016-01-31 18:12
Thanks for this, but I think the problem is with ```readxl::read_excel``` and not ```fulltext```. I ran your package through win-builder changing the offending line in the vignette to only include ```ft_get_si``` (...and then deleting the rest of the vignette), and it passed the win-builder build with no problems. You can see for yourself here: http://win-builder.r-project.org/i43SI6RN9P4u/

Opening Excel files is a much harder thing than you might think (some packages use Java somehow, I think...!), and I imagine something is a bit off with win-builder. This would also explain why all the test badges on your repo work.

If this is something that's worrying you, I'd suggest either (1) moving to a static vignette (I can't reproduce this on a machine that I can sit at), or (2) changing to another package (```gdata``` is my favourite for Excel). (2) is probably best.

I appreciate this isn't probably the answer you were hoping for, but given it doesn't look like a ```fulltext``` problem I can't think of much more to suggest. Please correct me if I've done something wrong!...

**Comment by fmichonneau** [comment] 2016-01-31 18:24
Thanks for looking into it @willpearse. You'd think reading Excel files would be the easiest on Windows :) I'll investigate further.

**Comment by willpearse** [comment] 2016-01-31 18:29
...I see your point :D Glad I could help...
